<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
 
$productRepository = $objectManager->get('\Magento\Catalog\Model\ProductRepository');
 
// get product by product id 
$product = $productRepository->getById(2074);
 
// get product by product sku 
$product = $productRepository->get('MT12');
 
echo $product->getEntityId() . '<br>';
echo $product->getName() . '<br>';
echo $product->getSKU() . '<br>';
echo $product->getPrice() . '<br>';
echo $product->getSpecialPrice() . '<br>';
echo $product->getTypeId() . '<br>';
echo $product->getProductUrl() . '<br>';