<form id="comment-form" action="<?php echo $block->getFormAction(); ?>" method="post">

    <fieldset class="fieldset">
        <legend class="legend"><span><?php /* @escapeNotVerified */ echo __('Add new comment') ?></span></legend><br>
        <div class="note"></div>
        <div class="field required">
            <label for="author" class="label">
                <span><?php /* @escapeNotVerified */ echo __('Email') ?></span>
            </label>

            <div class="control">
                <input type="text" id="author"
                       name="email"
                       class="input-text" width="50%">
            </div>
        </div>
        <div class="field required">
            <label for="content" class="label">
                <span><?php /* @escapeNotVerified */ echo __('Content') ?></span>
            </label>

            <div class="control">
                <textarea id="content"
                       name="content"
                       class="input-text"></textarea>
            </div>
        </div>
    </fieldset>
    <input type="hidden" name="post_id" value="<?php echo $block->getPostID() ?>"/>
    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" id="comment_ajax" class="action submit primary" title="<?php /* @escapeNotVerified */ echo __('Submit') ?>">
                <span><?php /* @escapeNotVerified */ echo __('Submit') ?></span>
            </button>
        </div>
    </div>
</form>
<?php $form_url = $block->getCommentAjaxAction(); ?>
<script type="text/x-magento-init">
    {
        "*": {
            "OpenTechiz_Blog/js/commentajax": {
                "AjaxCommentPostUrl": "<?php echo $form_url; ?>"
            }
        }
    }
</script>