<div class="container">
	<div class="row">
		<div class="col-sm-6">
			<div class="contactinfo">
				<ul class="nav nav-pills">
					<li><a href="#"><i class="fa fa-phone"></i><?php echo $this->getData('store_phone'); ?></a></li>
					<li><a href="#"><i class="fa fa-envelope"></i> <?php echo $this->getData('store_email'); ?><</a></li>
				</ul>
			</div>
		</div>
		<div class="col-sm-6">
			<div class="social-icons pull-right">
				<ul class="nav navbar-nav">
					<li><a href="<?php echo $this->getData('store_facebook'); ?>">fb</a></li>
					<li><a href="<?php echo $this->getData('store_twitter'); ?>">tw</i></a></li>
					<li><a href="#">link</i></a></li>
					<li><a href="#">sd</a></li>
					<li><a href="#">gg</i></a></li>
				</ul>
			</div>
		</div>
	</div>
</div>